[project]
name = "energy-price-api"
version = "1.0.0"
description = "A package to fetch and provide energy prices."
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "google-genai>=2.25.0",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
]

[tool.uv]
required-version = ">=0.12.19"
